// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$0 from "./sections/Articles.tsx";
import * as $$$$$$1 from "./sections/Benefit.tsx";
import * as $$$$$$2 from "./sections/CardsSection.tsx";
import * as $$$$$$3 from "./sections/Footer.tsx";
import * as $$$$$$4 from "./sections/Header.tsx";
import * as $$$$$$5 from "./sections/Hero.tsx";
import * as $$$$$$6 from "./sections/MediaSection.tsx";
import * as $$$$$$7 from "./sections/ParagraphList.tsx";
import * as $$$$$$8 from "./sections/Question.tsx";
import * as $$$$$$9 from "./sections/SectionBlog.tsx";
import * as $$$$$$10 from "./sections/SectionInvestors.tsx";
import * as $$$$$$11 from "./sections/SectionPartenes.tsx";
import * as $$$$$$12 from "./sections/SimpleTextList.tsx";
import * as $$$$$$13 from "./sections/SlideNews.tsx";
import * as $$$$$$14 from "./sections/TableInfos.tsx";
import * as $$$$$$15 from "./sections/Theme.tsx";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";

const manifest = {
  "sections": {
    "deco-sites/site-cora/sections/Articles.tsx": $$$$$$0,
    "deco-sites/site-cora/sections/Benefit.tsx": $$$$$$1,
    "deco-sites/site-cora/sections/CardsSection.tsx": $$$$$$2,
    "deco-sites/site-cora/sections/Footer.tsx": $$$$$$3,
    "deco-sites/site-cora/sections/Header.tsx": $$$$$$4,
    "deco-sites/site-cora/sections/Hero.tsx": $$$$$$5,
    "deco-sites/site-cora/sections/MediaSection.tsx": $$$$$$6,
    "deco-sites/site-cora/sections/ParagraphList.tsx": $$$$$$7,
    "deco-sites/site-cora/sections/Question.tsx": $$$$$$8,
    "deco-sites/site-cora/sections/SectionBlog.tsx": $$$$$$9,
    "deco-sites/site-cora/sections/SectionInvestors.tsx": $$$$$$10,
    "deco-sites/site-cora/sections/SectionPartenes.tsx": $$$$$$11,
    "deco-sites/site-cora/sections/SimpleTextList.tsx": $$$$$$12,
    "deco-sites/site-cora/sections/SlideNews.tsx": $$$$$$13,
    "deco-sites/site-cora/sections/TableInfos.tsx": $$$$$$14,
    "deco-sites/site-cora/sections/Theme.tsx": $$$$$$15,
  },
  "apps": {
    "deco-sites/site-cora/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/site-cora/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/site-cora",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
